version: '3'
services:
  mariadb:
    container_name: mariadb
    #image: docker.io/bitnami/mariadb:11.2
    image: docker.io/bitnami/mariadb
    environment:
      # - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_PASSWORD=foobar1111
      - MARIADB_ROOT_PASSWORD=foobar1111
      - MARIADB_USER=moodle
      - MARIADB_DATABASE=moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    networks:
      - local-keycloak
  moodle:
    container_name: moodle 
    #image: docker.io/bitnami/moodle:4.3
    image: docker.io/bitnami/moodle
    ports:
      - '8000:8080'
      - '443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=moodle
      - MOODLE_DATABASE_NAME=moodle
      - MOODLE_DATABASE_PASSWORD=foobar1111
      - MOODLE_DATABASE_ROOT_PASSWORD=foobar1111
      - MOODLE_SITE_NAME=moodle-cas.local
      - MOODLE_USERNAME=foobar_user
      - MOODLE_PASSWORD=foobar1111
      # - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    networks:
      - local-keycloak

networks:
  local-keycloak:
  
volumes:
  mariadb_data:
#    driver: local
  moodle_data:
#    driver: local
  moodledata_data:
#    driver: local

